# Revisão

def inicia a definição de uma função

In [2]:
def parabola(x,a,b,c):
    y = a*x**2+b*x+c
    return y

parabola(1,5,2,4)

11

Funções com argumentos com valor padrão:

In [3]:
def parabola_2(x,a=5,b=2,c=4):
    y = a*x**2+b*x+c
    return y
    
parabola_2(1)


11

Funções anônimas podem ser criadas com a palavra-chave lambda. As funções lambdas são restritas a uma única (em geral pequena) expressão. 

In [4]:
def quadrado(x):
    return x**2

f=quadrado(7)
print(f)

49


In [5]:
f2 = lambda x: x**2

f2(6)

36

In [6]:
f_soma = lambda a,b: a+b
f_soma(5,9)

14

# Estrutura de dados

Veja a seguir mais métodos de objetos do tipo lista:

In [7]:
l=[5,18,43,77,91,18,77]

Adicionar um elemento ao final da lista

In [8]:
l.append(100)
print(l)

[5, 18, 43, 77, 91, 18, 77, 100]


Inserir um elemento em uma dada posição. Nesse caso insere o elemento 9 na posição de índice 1. 

In [9]:
l.insert(1,9)
print(l)

[5, 9, 18, 43, 77, 91, 18, 77, 100]


Remover o primeiro elemento da lista que tem valor igual ao argumento (nesse caso remove o elemento 18)

In [10]:
l.remove(18)
print(l)

[5, 9, 43, 77, 91, 18, 77, 100]


Contar o número de vezes que um elemento aparece na lista

In [11]:
l.count(77)

2

In [12]:
print(l)

[5, 9, 43, 77, 91, 18, 77, 100]


Remover o elemento em uma dada posição. Esse método remove o elemento e o retorna. 

Nesse caso remove o elemento de índice 1.

In [13]:
l.pop(1)

9

In [14]:
print(l)

[5, 43, 77, 91, 18, 77, 100]


Devolver o índice do primeiro elemento cujo valor é igual ao argumento (nesse caso 91)


In [15]:
l.index(91)

3

In [16]:
l.index(77)

2

In [17]:
l.index(53)

ValueError: ignored

Ordenar os elementos da lista

In [19]:
print("lista:",l)
l.sort()
print("lista ordenada:", l)

lista: [5, 18, 43, 77, 77, 91, 100]
lista ordenada: [5, 18, 43, 77, 77, 91, 100]


Ordenar em ordem reversa

In [20]:
l=[5, 43, 77, 91, 18, 77, 100]  #definindo novamente a lista l
l.sort(reverse=True)  
print(l)

[100, 91, 77, 77, 43, 18, 5]


Inverter a ordem dos elementos

In [21]:
l=[5, 43, 77, 91, 18, 77, 100] #definindo novamente a lista l
l.reverse()   
print(l)

[100, 77, 18, 91, 77, 43, 5]


Copiar os elementos da lista

In [22]:
l_c=l.copy()
print(l_c)

[100, 77, 18, 91, 77, 43, 5]


Para iterar sobre uma lista, a posição e o valor podem ser obtidos simultaneamente com a função enumerate()

In [23]:
for i, v in enumerate(l_c):
    print(i,v)

0 100
1 77
2 18
3 91
4 77
5 43
6 5


Para percorrer duas ou mais listas ao mesmo tempo, as entradas podem ser pareadas com a função zip()

In [26]:
l1=[2.5,3.9,8.7]    # definindo lista l1
l2=[8.7,23.4,12.5]    # definindo lista l2
for a,b in zip(l1,l2):
    print(a,b)

2.5 8.7
3.9 23.4
8.7 12.5


Uma lista pode ser percorrida na ordem inversa com a função reversed()

In [24]:
for z in reversed(range(10)):
    print(z)

9
8
7
6
5
4
3
2
1
0


**Compreensões de listas**

Compreensões de listas são uma maneira concisa de criar uma lista. Uma aplicação comum é criar uma nova lista onde cada elemente é resultante da avaliação de uma expressão no contexto das cláusulas for e if. 

Por exemplo, podemos criar uma lista com os quadrados desta forma:


In [27]:
quadrados=[]     # cria uma lista vazia e armazena na variável quadrados
for x in range(10):
    quadrados.append(x**2)
    
print(quadrados)

[0, 1, 4, 9, 16, 25, 36, 49, 64, 81]


Alternativamente, podemos fazer:

In [28]:
quadrados2=[x**2 for x in range(10)]
print(quadrados2)

[0, 1, 4, 9, 16, 25, 36, 49, 64, 81]


In [29]:
quadrados3=list(map(lambda x: x**2, range(10)))
print(quadrados3)

[0, 1, 4, 9, 16, 25, 36, 49, 64, 81]


**Tuplas**

Uma tupla consiste em uma sequência de valores separados por vírgulas. Na sua criação os valores de uma tupla podem ser envolvidos ou não por parênteses. Na saída do console tuplas são sempre envolvidas por parênteses. Apesar de serem similares às listas, as tuplas são frequentemente utilizadas em situações e com propósitos distintos. O principal motivo é que tuplas são imutáveis, enquanto listas são mutáveis. 

In [30]:
t= 5, 87, 'bla'
print(t)

(5, 87, 'bla')


In [31]:
print(t[0])

5


In [32]:
u=t,(56,89,346)  
print(u)

((5, 87, 'bla'), (56, 89, 346))


Tuplas são **imutáveis**

In [33]:
t[0]=65

TypeError: ignored

In [34]:
v=(27.6,45.9)  #empacotamento em uma tupla
vx, vy = v   #processo inverso de desempacotamento também é possível
print(vx)

27.6



**Dicionários** 

Uma estrutura de dados muito útil é o dicionário. Eles são indexados por palavras-chaves (keys), que podem ser de qualquer tipo imutável. Os dicionários são delimitados por {} e contém uma lista de pares chave:valor separados por vírgulas. O dicionário vazio é {}. Os dicionários são utilizados para armazenar e recuperar valores a partir das palavras-chaves. É possivel substituir uma valor de uma chave por um novo valor. 

In [35]:
ramais = {'Cristina': 6473, 'Ana': 6486, 'Marina': 7256, 'Allan': 7257,'Gustavo': 7257 }
print(ramais['Marina'])

7256


Remover um par chave:valor

In [36]:
del(ramais['Allan'])
print(ramais)

{'Cristina': 6473, 'Ana': 6486, 'Marina': 7256, 'Gustavo': 7257}


Incluir novo par chave:valor

In [37]:
ramais['Charles'] = 6486
print(ramais)

{'Cristina': 6473, 'Ana': 6486, 'Marina': 7256, 'Gustavo': 7257, 'Charles': 6486}


Alterar o valor de uma chave

In [38]:
ramais['Cristina']=6478
print(ramais)

{'Cristina': 6478, 'Ana': 6486, 'Marina': 7256, 'Gustavo': 7257, 'Charles': 6486}


Listar todas as chaves presentes no dicionário 

In [39]:
list(ramais)

['Cristina', 'Ana', 'Marina', 'Gustavo', 'Charles']

Verificar se uma está ou não no dicionário

In [40]:
'Cristina' in ramais

True

In [41]:
'Sandra' in ramais

False

O construtor dict cria um dicionário a partir de sequências de pares chave,valor

In [42]:
dict([('Cristina',6473), ('Ana',6486),('Marina',7256)])

{'Ana': 6486, 'Cristina': 6473, 'Marina': 7256}

In [43]:
dict(Allan=7257,Charles=6486)

{'Allan': 7257, 'Charles': 6486}

As compreensões de dicionário também podem ser usadas para criar dicionários a partir de expressões

In [44]:
{x: x**2 for x in range(10)}

{0: 0, 1: 1, 2: 4, 3: 9, 4: 16, 5: 25, 6: 36, 7: 49, 8: 64, 9: 81}

Ao iterar sobre dicionários, a chave e o valor podem ser obtidos simultaneamente usando o método items()

In [45]:
for nome,fone in ramais.items():
    print(nome,fone)

Cristina 6478
Ana 6486
Marina 7256
Gustavo 7257
Charles 6486


# Módulos

Uma boa prática ao escrever códigos maiores é dividí-lo em arquivos menores, o que pode facilitar a manutenção. 

Um módulo é um arquivo contendo definições e instruções Python. O nome do arquivo é o nome do módulo acrescido do sufixo .py.

Um módulo também pode ser muito útil para escrever funções que são usadas em vários programas diferentes. É preferível usar um arquivo separado para uma função do que copiá-la para dentro de vários programas. 

Por exemplo, usando um editor de texto, foi criado um arquivo chamado fibonacci.py, contendo as funções fib e fib_lista, apresentadas na última aula. Ao importar um módulo, as funções definidas no arquivo são colocadas diretamente na tabelas de símbolos atual e poderão ser chamadas e executadas.  



In [46]:
import fibonacci

In [47]:
fibonacci.fib(20)

0 1 1 2 3 5 8 13 

In [48]:
fibonacci.fib_lista(20)

[0, 1, 1, 2, 3, 5, 8, 13]

Módulos podem importar outros módulos. É costume colocar todos os comandos de import no início do módulo ou de um programa. 

Outras maneiras de importar as definições de um módulo são:

In [49]:
from fibonacci import fib, fib_lista

In [50]:
from fibonacci import *
# Importa todos os nomed definidos em um módulo
# Nem sempre aconselhado, pois introduz um conjunto desconhecido de nomes no ambiente, podendo levar a conflitos 
# com outros nomes previamente definidos

In [53]:
import fibonacci as fibo
fibo.fib(10)

0 1 1 2 3 5 8 

In [54]:
from fibonacci import fib_lista as f_l
f_l(30)

[0, 1, 1, 2, 3, 5, 8, 13, 21]

O Python guarda versões compiladas de cada módulo no diretório \__ pycache__ com o nome modulo.versão.pyc para acelerar o carregamento de módulos. 

# Pacotes

Os pacotes são uma maneira de estruturar o “espaço de nomes” (namespace) dos módulos Python. Eles são uma coleção de módulos. Nos referimos a um módulo dentro de um pacote como nomedopacote.nomedomodulo. 

Os arquivos \__ init__.py são necessários para que o Python trate diretórios contendo o arquivo como pacotes. \__ init__.py pode ser apenas um arquivo vazio. 

O pacote **math** contém todas as funções matemáticas padrão (sqrt,log, log10, exp, funções trigonométricas). 

In [55]:
from math import log
x = log(3)
print(x)

1.0986122886681098


In [56]:
from math import pi
print(pi)

3.141592653589793


In [57]:
from math import exp
from math import sin, cos

In [58]:
from math import *

In [59]:
# Algoritmo para converter a posição de um ponto dada em coordenadas polares (r,theta) para coordenadas 
# Cartesianas (x,y)

from math import sin,cos,pi

r = float(input('Entre o valor de r: '))
d = float(input('Entre o valor de theta em graus: '))

theta = d*pi/180. #conversão de graus para radianos
x = r*cos(theta)
y = r*sin(theta)

print('x=', x, 'y=',y)


Entre o valor de r: 3
Entre o valor de theta em graus: 30
x= 2.598076211353316 y= 1.4999999999999998


O pacote **numpy** é fundamental para computação científica com Python. Ele oferece funções matemáticas, geradores de números aleatórios, rotinas de álgebra linear, transformada de Fourier e muito mais. Mas o seu poder está em permitir cálculos em arrays multidimensionais. 

O numpy executa facilmente cálculos numéricos que são muito utilizados em problemas de machine learning (aprendizado de máquina) e de processamento de imagem (imagens no computador são representadas como arrays multidimensionais de números). Além disso, o numpy oferece várias outras tarefas matemáticas.

Para mais informações, consulte https://numpy.org/. 

# Arrays

Um array é um conjunto ordenado de valores. Mas há diferenças importantes entre listas e arrays:
* O número de elementos de um array é fixo e não é possível adicionar ou remover elementos de um array após criá-lo;
* Os elementos de um array devem ser todos de um mesmo tipo, como float ou inteiros.

As principais vantagens de usar arrays em vez de listas são:
* Arrays podem ter qualquer número de dimensões. Arrays unidimensionais e bidimensionais são, respectivamente, como vetores e matrizes em álgebra linear. Listas são sempre unidimensionais. 
* Como se comportam como vetores ou matrizes, podemos fazer qualquer aritmética com eles, ao contrário de listas.
* Arrays funcionam mais rápido que listas em Python.

Cada dimensão de um array é chamada axis. O número de axes é chamada de rank do array. A indexação dos arrays também começa em 0, com um número para cada axis do array.


In [60]:
from numpy import array

a = array([[1,2,3],[4,5,6],[7,8,9]])

print(a)


[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [72]:
# Minha recomendação
import numpy as np

a = np.array([[1,2,3],[4,5,6],[7,8,9]])

print(a)

[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]


In [68]:
type(a)  # checar que o tipo é um numpy array

numpy.ndarray

In [71]:
a.dtype  # fornece o tipo dos elementos do array


dtype('float64')

In [73]:
a.shape   # dimensões do array

(3, 3)

In [74]:
a.ndim   # número de dimensões 

2

In [75]:
a.size   # número de elementos 

9

Indexação de um array: o índice da linha vem primeiro e depois o da coluna

In [76]:
print(a)

[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]


In [78]:
print(a[2,1])

8.0


In [79]:
# fatiando um array
a[1,:]

array([4., 5., 6.])

In [ ]:
a[:,0]

array([1, 4, 7])

In [ ]:
a[1,0:2]

array([4, 5])

Iterando sobre um array


In [80]:
b = np.array([0,2,5,8],dtype=int)
print(b)

[0 2 5 8]


In [ ]:
for z in b:
    print(z)

0
2
5
8


In [ ]:
for i in range(len(b)):
    print(b[i])

0
2
5
8


Outras formas de criar arrays


In [ ]:
a0 = np.zeros(5)
print(a0)

[0. 0. 0. 0. 0.]


In [ ]:
a0_2 = np.zeros([3,4])
print(a0_2)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [ ]:
a1 = np.ones(7)
print(a1)

[1. 1. 1. 1. 1. 1. 1.]


In [ ]:
a1_2 = np.ones([2,3])
print(a1_2)

[[1. 1. 1.]
 [1. 1. 1.]]


In [ ]:
a1_3 = np.ones([2,3,4])
print(a1_3)

[[[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]]


In [ ]:
# A função arange retorna valores espaçados igualmente em um certo intervalo. 
# O espaçamento é definido pelo passo (terceiro argumento da função).
# numpy.arange(início,fim,passo)
a2 = np.arange(1.,4.,0.5)
print(a2)

[1.  1.5 2.  2.5 3.  3.5]


In [84]:
# A função linspace também retorna n valores espaçados igualmente em um certo intervalo. 
# numpy.linspace(início,fim,n) 
a3 = np.linspace(1.,10.,6)
print(a3)

[ 1.   2.8  4.6  6.4  8.2 10. ]


In [85]:
l=[2,5,9]
a4 = np.array(l,float)
print(a4)

[2. 5. 9.]


In [ ]:
a5 = np.random.rand(3,4)
print(a5)

[[0.43571433 0.20533201 0.98174447 0.84546266]
 [0.83801409 0.69056924 0.04905891 0.08388357]
 [0.22183565 0.08117122 0.82514679 0.81113755]]


Operações com arrays

In [ ]:
c = np.array([1,2])
d = np.array([3,4])

print(c+d)

[4 6]


In [ ]:
print(c*d)

[3 8]


In [ ]:
print(c**d)

[ 1 16]


In [ ]:
e = a1_2+6.5
print(e)

[[7.5 7.5 7.5]
 [7.5 7.5 7.5]]


In [ ]:
#Produto escalar de dois array é feito pela função dot
prod_esc = np.dot(c,d)
print(prod_esc)

11


In [ ]:
log10_c = np.log10(a5)
print(log10_c)

[[-0.36079816 -0.68754333 -0.00800154 -0.07290557]
 [-0.07674868 -0.16079277 -1.30928209 -1.07632309]
 [-0.65396867 -1.09059794 -0.08346878 -0.09090549]]


In [ ]:
a = np.array([1,1])
b = a
a[0] = 2
print(a)
print(b)

[2 1]
[2 1]


In [ ]:
a = np.array([1,1])
b = np.copy(a)
a[0] = 2
print(a)
print(b)

[2 1]
[1 1]
